Rebuilding for Titanium SDK 6.0.0+
omorandi/tiws pull request #34
Opened 2016-11-17 14:17 UTC by gimdongwoo

2016-11-24 08:55 UTC, omorandi requested changes
Thanks for the PR, looks good. If you change the new module version, I'd be happy to merge it.

2016-11-24 08:55 UTC, omorandi commented on android/manifest
> +version: 1.1.0
Maybe it would be better to bump the major number to 2.0.0 here, since it's a breaking change, incompatible with previous Titanium versions

2016-11-24 09:03 UTC, merged

2016-11-24 09:03 UTC, omorandi commented
thank you

2017-01-17 17:06 UTC, chmiiller commented
Great! Thank you @gimdongwoo